### PR TITLE
Lz4

### PR DESCRIPTION
**Pull request by ghost**
Adds support for LZ4 compression.
Need dependency python-lz4
Sorry, I don't know how to fix setup.py to reflect changes.

### CODE REVIEW

**Comment by ghost** [comment]
`python setup.py test` currently gives `return handler.read(path, mode[:2])` and `return handler.write(path, mode[:2])` incorrect values. Namely `r|` and `w|`.

nvm I'm an uneducation pleb. I fixed it.

**Review by c-w — COMMENTED** [review]
Thanks for the contribution! Overall this looks good.

In order to make the setup work, I'd suggest to declare an [extra dependency](https://www.python.org/dev/peps/pep-0508/#extras) on the [lz4 module](https://pypi.org/project/lz4/) similar to [what's being done for zstandard in setup.py](https://github.com/ascoderu/xtarfile/blob/b3a48d808417bf5a153f4f9d7607a56db0d39460/setup.py#L27-L29), e.g. like this:

```diff
    extras_require={
+       'lz4': ['lz4 >= 3.1.1'],
        'zstd': ['zstandard >= 0.10.2']
    },
```

We'll then also need to install the new dependency in the CI workflow so that the tests can pick up the module, again similar to [what's being done for zstandard in ci.yml](https://github.com/ascoderu/xtarfile/blob/b3a48d808417bf5a153f4f9d7607a56db0d39460/.github/workflows/ci.yml#L35), e.g. like this:

```diff
-     - run: pip install -e .[zstd]
+     - run: pip install -e .[lz4,zstd]
      - run: python setup.py test
```

**Comment by ghost** [comment]
Set the lz4 version to 2.2.1 because that's what I tested on during development.

**Review by c-w — APPROVED** [review]
LGTM! 🚢

**Comment by c-w** [comment]
Released in version [0.1.0](https://pypi.org/project/xtarfile/0.1.0).

**Comment by nzola** [comment]
@meganomic @c-w Thanks!

**Comment by nzola** [comment]
Hi @meganomic Would you be willing to contribute in other issues as well? We really appreciated your contribution.

**Comment by ghost** [comment]
@nzola By other issues I assume you mean with the lokole project. I checked out some of the issues and and unfortunately most of them seem to be above my skill level. I'm just a hobby programmer. The only place I see I can be of use is with writing tests or other minor tasks. I'm currently working on another PR for xtarfile but after that is done I'll look into it.

**Comment by nzola** [comment]
@meganomic Yes, issues for Lokole system. Thanks for willing to do more. If
you have other programmer friends, invite them to contribute to the Lokole
project. This project will soon help millions of the people in the Congo
DRC who are excluded from the digital contents due to poverty and cannot
access the Internet world.

Cheers,
Nzola

**Pull request merged**
