### PR TITLE
recognise short tarfile extensions

### PR DESCRIPTION
**Pull request by Keou0007**
Adds ability to handle files with short tarfile extensions. i.e. `file.tzst` instead of `file.tar.zst`

### CODE REVIEW

**Comment by c-w** [comment]
Change looks good.

The CI is failing as this project hasn't seen an update in forever. Could you update the test matrix ([here](https://github.com/ascoderu/xtarfile/blob/51120c93adf3223ac789206661339c8fecc3788c/.github/workflows/ci.yml#L26)) to include only Python 3.8 to 3.11 and also update the deploy pipeline ([here](https://github.com/ascoderu/xtarfile/blob/51120c93adf3223ac789206661339c8fecc3788c/.github/workflows/cd.yml#L16)) to always run on the latest stable Python 3.x. Thank you :pray: and I'll get this released ASAP.

**Comment by Keou0007** [comment]
I think I've done that right. CI/CD is not something I have huge experience with ¯\ \_(ツ)\_/¯

**Comment by c-w** [comment]
Yes, great, thank you.

**Comment by c-w** [comment]
Slight delay in getting this published as I need to figure out access permissions to the PyPI account that owns this package. I'll update when it's live.

**Comment by c-w** [comment]
This has been released in [0.2.0](https://pypi.org/project/xtarfile/0.2.0/), thanks for submitting the pull request.

**Pull request merged**
